# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 20:34
from __future__ import unicode_literals

import datetime
from decimal import Decimal
import digifoot.lib.django.models
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SparkDeviceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('deleted_at', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc), verbose_name='Deleted at')),
                ('spark_id', models.CharField(max_length=255, unique=True)),
                ('engaged', models.BooleanField(default=False)),
                ('locked', models.BooleanField(default=False)),
                ('image', models.URLField(default='https://scontent.xx.fbcdn.net/hphotos-xft1/v/t1.0-9/11390213_986530648032320_1564579499120820132_n.jpg?oh=1a2db0db77a6087d6b37f5805c6885ef&oe=562C5A4E')),
                ('location_lng', models.DecimalField(decimal_places=3, default=Decimal('52.519558'), max_digits=10)),
                ('location_lat', models.DecimalField(decimal_places=3, default=Decimal('13.423086'), max_digits=10)),
            ],
            options={
                'ordering': ('created_at', 'pk'),
                'abstract': False,
            },
            bases=(digifoot.lib.django.models.ModelMixins, models.Model),
        ),
    ]
