# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 21:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sparks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparkdevicemodel',
            name='engaged',
        ),
        migrations.RemoveField(
            model_name='sparkdevicemodel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='sparkdevicemodel',
            name='location_lat',
        ),
        migrations.RemoveField(
            model_name='sparkdevicemodel',
            name='location_lng',
        ),
        migrations.RemoveField(
            model_name='sparkdevicemodel',
            name='locked',
        ),
    ]
