# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-12 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparks', '0004_sparkdevicemodel_org_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparkdevicemodel',
            name='goal_limit',
            field=models.IntegerField(default=10),
        ),
    ]
