# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-12 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparks', '0006_auto_20160312_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparkdevicemodel',
            name='PUSHER_APP_ID',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sparkdevicemodel',
            name='PUSHER_CLUSTER',
            field=models.TextField(blank=True),
        ),
    ]
