# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 21:00
from __future__ import unicode_literals

import datetime
import digifoot.lib.django.models
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sparks', '0002_auto_20151209_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('deleted_at', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc), verbose_name='Deleted at')),
                ('whites', models.BooleanField()),
            ],
            options={
                'ordering': ('created_at', 'pk'),
                'abstract': False,
            },
            bases=(digifoot.lib.django.models.ModelMixins, models.Model),
        ),
        migrations.CreateModel(
            name='MatchModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('deleted_at', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc), verbose_name='Deleted at')),
                ('finished', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('created_at', 'pk'),
                'abstract': False,
            },
            bases=(digifoot.lib.django.models.ModelMixins, models.Model),
        ),
        migrations.CreateModel(
            name='PlayerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('deleted_at', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc), verbose_name='Deleted at')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ('created_at', 'pk'),
                'abstract': False,
            },
            bases=(digifoot.lib.django.models.ModelMixins, models.Model),
        ),
        migrations.AddField(
            model_name='matchmodel',
            name='black_side_matches',
            field=models.ManyToManyField(related_name='black_side_matches', to='league.PlayerModel'),
        ),
        migrations.AddField(
            model_name='matchmodel',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='sparks.SparkDeviceModel'),
        ),
        migrations.AddField(
            model_name='matchmodel',
            name='white_side_matches',
            field=models.ManyToManyField(related_name='white_side_matches', to='league.PlayerModel'),
        ),
        migrations.AddField(
            model_name='goalmodel',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.MatchModel'),
        ),
    ]
