# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_auto_20151209_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchmodel',
            name='black_side_matches',
        ),
        migrations.RemoveField(
            model_name='matchmodel',
            name='white_side_matches',
        ),
        migrations.AddField(
            model_name='matchmodel',
            name='black_side_players',
            field=models.ManyToManyField(related_name='black_side_players', to='league.PlayerModel'),
        ),
        migrations.AddField(
            model_name='matchmodel',
            name='white_side_players',
            field=models.ManyToManyField(related_name='white_side_players', to='league.PlayerModel'),
        ),
    ]
