# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 00:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_auto_20151209_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchmodel',
            name='finished_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
