# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_matchmodel_finished_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchmodel',
            name='tweeted',
            field=models.BooleanField(default=False),
        ),
    ]
