# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-12 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_matchmodel_tweeted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchmodel',
            options={},
        ),
        migrations.AlterField(
            model_name='matchmodel',
            name='finished',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterIndexTogether(
            name='matchmodel',
            index_together=set([('device', 'finished')]),
        ),
    ]
